Header header
geometry_msgs/Point[] point

int32 JointType_SpineBase=0
int32 JointType_SpineMid=1
int32 JointType_Neck=2
int32 JointType_Head=3
int32 JointType_ShoulderLeft=4
int32 JointType_ElbowLeft=5
int32 JointType_WristLeft=6
int32 JointType_HandLeft=7
int32 JointType_ShoulderRight=8
int32 JointType_ElbowRight=9
int32 JointType_WristRight=10
int32 JointType_HandRight=11
int32 JointType_HipLeft=12
int32 JointType_KneeLeft=13
int32 JointType_AnkleLeft=14
int32 JointType_FootLeft=15
int32 JointType_HipRight=16
int32 JointType_KneeRight=17
int32 JointType_AnkleRight=18
int32 JointType_FootRight=19
int32 JointType_SpineShoulder=20
int32 JointType_HandTipLeft=21
int32 JointType_ThumbLeft=22
int32 JointType_HandTipRight=23
int32 JointType_ThumbRight=24
int32 JointType_Count=25


int32 TrackingState_NotTracked=0
int32 TrackingState_Inferred=1
int32 TrackingState_Tracked=2